name: Persuasion Equation
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4108853046782315
title: Persuasion Equation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b8fd99'
    - '#14c3a2'
    - '#ff1f4c'
    - '#a85163'
    - '#41807a'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
